services:
  - type: web
    name: html-extractor-gpt
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: oregon
    branch: main
    runtime: node
    nodeVersion: 20.11.1
    autoDeploy: true